/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab4.h"

#include <rpc/rpc.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define N 1024

int main(int argc, char* argv[])
{
    CLIENT* client;
    uint32_t* num_packages;
    struct package* pkg;
    FILE* output_file;
    char* server_host;

    if (argc != 2) {
        fprintf(stderr, "Usage: %s <server_host>\n", argv[0]);
        exit(1);
    }

    server_host = argv[1];
    printf("Creating RPC client\n");
    // Create RPC client
    client = clnt_create(server_host, FILE_TRANSFER_PROG, FILE_TRANSFER_VERS, "udp");
    if (client == NULL) {
        clnt_pcreateerror(server_host);
        exit(1);
    }
    printf("Requesting number of packages\n");
    // Request the number of packages
    num_packages = request_num_packages_1(NULL, client);
    if (num_packages == NULL) {
        clnt_perror(client, "Failed to request number of packages");
        exit(1);
    }

    printf("Number of packages: %d\n", *num_packages);

    output_file = fopen("received_video.mp4", "wb");
    if (output_file == NULL) {
        perror("Failed to open output file");
        exit(1);
    }

    printf("Requesting all packages...\n");
    // Request and receive all packages
    for (uint32_t i = 1; i <= *num_packages; i++) {
        printf("Requesting package %d\n", i);
        pkg = request_package_1(&i, client);
        if (pkg == NULL) {
            clnt_perror(client, "Failed to request package");
            break;
        }

        fwrite(pkg->data, 1, pkg->size, output_file);
        printf("Received package %d (%d bytes)\n", pkg->id, pkg->size);
    }

    fclose(output_file);
    clnt_destroy(client);

    printf("File reception completed.\n");
    return 0;
}
