/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab4.h"
#include <rpc/rpc.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FILENAME "toSend.mp4"
#define N 1024

FILE* file = NULL;
uint32_t num_packages = 0;

uint32_t* request_num_packages_1_svc(void* arg, struct svc_req* rqstp)
{
    static uint32_t result;

    if (file == NULL) {
        file = fopen(FILENAME, "rb");
        if (file == NULL) {
            perror("Failed to open file");
            result = -1;
            return &result;
        }
    }

    fseek(file, 0, SEEK_END);
    long file_size = ftell(file);
    rewind(file);

    num_packages = (file_size + N - 1) / N;
    result = num_packages;

    return &result;
}

struct package* request_package_1_svc(uint32_t* package_id, struct svc_req* rqstp)
{
    static struct package result;
    uint32_t id = *package_id;

    if (file == NULL) {
        file = fopen(FILENAME, "rb");
        if (file == NULL) {
            perror("Failed to open file");
            result.id = 0;
            result.size = 0;
            return &result;
        }
    }

    if (id > num_packages) {
        result.id = 0;
        result.size = 0;
        return &result;
    }

    fseek(file, (id - 1) * N, SEEK_SET);

    result.id = id;
    result.size = fread(result.data, 1, N, file);

    return &result;
}
