/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "lab4.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

uint32_t *
request_num_packages_1(void *argp, CLIENT *clnt)
{
	static uint32_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_num_packages,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_uint32_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

package *
request_package_1(uint32_t *argp, CLIENT *clnt)
{
	static package clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_package,
		(xdrproc_t) xdr_uint32_t, (caddr_t) argp,
		(xdrproc_t) xdr_package, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
