/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lab4.h"

bool_t
xdr_package (XDR *xdrs, package *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_uint32_t (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->data, 1024))
		 return FALSE;
	return TRUE;
}
