/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAB4_H_RPCGEN
#define _LAB4_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct package {
	uint32_t id;
	uint32_t size;
	char data[1024];
};
typedef struct package package;

#define FILE_TRANSFER_PROG 0x31234567
#define FILE_TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define request_num_packages 1
extern  uint32_t * request_num_packages_1(void *, CLIENT *);
extern  uint32_t * request_num_packages_1_svc(void *, struct svc_req *);
#define request_package 2
extern  package * request_package_1(uint32_t *, CLIENT *);
extern  package * request_package_1_svc(uint32_t *, struct svc_req *);
extern int file_transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define request_num_packages 1
extern  uint32_t * request_num_packages_1();
extern  uint32_t * request_num_packages_1_svc();
#define request_package 2
extern  package * request_package_1();
extern  package * request_package_1_svc();
extern int file_transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_package (XDR *, package*);

#else /* K&R C */
extern bool_t xdr_package ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LAB4_H_RPCGEN */
